// Code generated by mockery v2.53.3. DO NOT EDIT.

package translation

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

type MockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessor) EXPECT() *MockProcessor_Expecter {
	return &MockProcessor_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function with given fields: ctx, data
func (_m *MockProcessor) Translate(ctx context.Context, data []byte) ([]byte, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProcessor_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockProcessor_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockProcessor_Expecter) Translate(ctx interface{}, data interface{}) *MockProcessor_Translate_Call {
	return &MockProcessor_Translate_Call{Call: _e.mock.On("Translate", ctx, data)}
}

func (_c *MockProcessor_Translate_Call) Run(run func(ctx context.Context, data []byte)) *MockProcessor_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockProcessor_Translate_Call) Return(_a0 []byte, _a1 error) *MockProcessor_Translate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProcessor_Translate_Call) RunAndReturn(run func(context.Context, []byte) ([]byte, error)) *MockProcessor_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mock := &MockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
