// Code generated by mockery v2.53.3. DO NOT EDIT.

package translation

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTranslateService is an autogenerated mock type for the TranslateService type
type MockTranslateService struct {
	mock.Mock
}

type MockTranslateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslateService) EXPECT() *MockTranslateService_Expecter {
	return &MockTranslateService_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function with given fields: ctx, payload
func (_m *MockTranslateService) Translate(ctx context.Context, payload []TranslatePayloadItem) ([]TranslatePayloadItem, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 []TranslatePayloadItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []TranslatePayloadItem) ([]TranslatePayloadItem, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []TranslatePayloadItem) []TranslatePayloadItem); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TranslatePayloadItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []TranslatePayloadItem) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTranslateService_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslateService_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []TranslatePayloadItem
func (_e *MockTranslateService_Expecter) Translate(ctx interface{}, payload interface{}) *MockTranslateService_Translate_Call {
	return &MockTranslateService_Translate_Call{Call: _e.mock.On("Translate", ctx, payload)}
}

func (_c *MockTranslateService_Translate_Call) Run(run func(ctx context.Context, payload []TranslatePayloadItem)) *MockTranslateService_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]TranslatePayloadItem))
	})
	return _c
}

func (_c *MockTranslateService_Translate_Call) Return(_a0 []TranslatePayloadItem, _a1 error) *MockTranslateService_Translate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTranslateService_Translate_Call) RunAndReturn(run func(context.Context, []TranslatePayloadItem) ([]TranslatePayloadItem, error)) *MockTranslateService_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTranslateService creates a new instance of MockTranslateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslateService {
	mock := &MockTranslateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
